services:
  db:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - 6379:6379
  api:
    image: api
    env_file:
      - .env
  scheduler:
    image: scheduler
    env_file:
      - .env
  offers-worker:
    image: offers-worker
    env_file:
      - .env
  bots:
    image: bots
    env_file:
      - .env
